#!/usr/bin/env sh
# SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Regenerate STEP-CATALOG.md from the core cucumber step definitions — the
# ground truth for which Gherkin steps are wired to vauchi-core. Run from the
# features repo root; assumes the vauchi workspace layout (sibling core/).
#
#   scripts/gen-step-catalog.sh [core-steps-dir]
#
# The catalog is the reuse contract: author new scenarios from it (see its
# header). Adding a step means adding a #[given/when/then] in core, then
# re-running this. `scripts/check-step-catalog.sh` (CI) reports how much of
# each feature the catalog already covers.
set -eu

STEPS="${1:-../core/vauchi-core/tests/steps}"
OUT="STEP-CATALOG.md"

if [ ! -d "$STEPS" ]; then
  echo "ERROR: core steps dir not found at '$STEPS'." >&2
  echo "Pass the path explicitly: scripts/gen-step-catalog.sh <dir>" >&2
  exit 1
fi

emit_kw() {
  kw="$1"
  grep -rhoE "#\[$kw\((expr = )?\"[^\"]*\"\)\]" "$STEPS"/*.rs 2>/dev/null \
    | sed -E "s/#\[$kw\((expr = )?\"//; s/\"\)\]\$//" \
    | sort -u \
    | while IFS= read -r pat; do printf -- '- `%s`\n' "$pat"; done
}

{
  cat <<'HEADER'
<!-- SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me> -->
<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- GENERATED by scripts/gen-step-catalog.sh — do not edit by hand. -->

# Core step vocabulary (catalog)

These are the Gherkin steps wired to `vauchi-core` via cucumber-rs
(`core/vauchi-core/tests/steps/*.rs`). A scenario built **only** from these
steps executes as a real test; a scenario with any other step is skipped
(see `problems/2026-07-04-cucumber-backgrounds-fail-silently`).

**Authoring guidance (write new scenarios pre-wired):**

1. Compose scenarios from the steps below — reuse is the point (the suite's
   original failure was ~1.2 uses per step pattern; a healthy suite reuses a
   small vocabulary). `{string}` / `{int}` are parameters.
2. Need a step that isn't here? Add a `#[given/when/then]` in the core steps
   crate first, then re-run `scripts/gen-step-catalog.sh` to update this file.
3. `scripts/check-step-catalog.sh` reports, per feature, how many steps the
   catalog already covers — aim to raise it.
4. Steps describing UI (`I tap …`, `I should see …`, colours) or two parties
   (`Alice and Bob exchange …`) are out of scope for the core runner — tag
   those features `@ui` / leave them for the multi-party harness.

HEADER

  printf '## Given (setup)\n\n'
  emit_kw given
  printf '\n## When (actions)\n\n'
  emit_kw when
  printf '\n## Then (assertions)\n\n'
  emit_kw then
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^- ' "$OUT") step patterns)."
